# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Viet Noms' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viet Noms
  pod 'Alamofire', '~> 4.7'

  target 'Viet NomsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Viet NomsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
